### ISSUE TITLE
Update payable not working properly

### ISSUE THREAD

**Issue by davidochoa** [inoobs/debtify#5]

**Comment by defeed** [comment]
@davidochoa What's the deal with this?

**Comment by davidochoa** [comment]
We haven't added update functionality @defeed.

So will move forward with it. One question from me was: I think update should only update future payable_items, so if the payable has some with due_on in the past even if they are unpaid, then these ones shouldn't get updated. And if the payable doesn't have any payable_items in the future, then either don't allow to update or just allow them to update the recurring to create new future payments starting from today.

The problem about it came up with gmailer plugin that you can fetch invoices from the past as well, which makes sense to keep track of all your payments in the application. But it added a bit of a question with the logic for update.

So what do you think?

**Comment by defeed** [comment]
I was thinking to ask this from user, but can be done later, so for now only update the future items only. As for those, that don't have future items, make due_on read-only and show a hint why it's read-only

**Comment by defeed** [comment]
There's another bug, that might fit here as well, when you create payable with recurring 'none', it ignores amount and due_on date

**Comment by davidochoa** [comment]
Ok I'll take a look :)

**Comment by davidochoa** [comment]
@defeed what do you mean with recurring 'none', it ignores the `amount` and `due_on`?

Just created a payable with none recurring
<img width="1107" alt="screen shot 2016-02-21 at 4 42 00 pm" src="https://cloud.githubusercontent.com/assets/5469462/13203172/409813ee-d8ba-11e5-984a-6655e8ec25fa.png">

And opening the update, also works:
<img width="1164" alt="screen shot 2016-02-21 at 4 45 11 pm" src="https://cloud.githubusercontent.com/assets/5469462/13203177/883ed264-d8ba-11e5-9322-a85b94488113.png">

**Comment by defeed** [comment]
@davidochoa clarification, due date must be in past

**Comment by davidochoa** [comment]
Aaah @defeed :D Alright, no problem, you scared me when you said bug. Yeah, all part of same functionality :)
