### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by davidochoa** [inoobs/debtify#6]
Dashboard with 2 tables:
- [x]  Coming up payments (5 or next 7 days payments, or tomorrow's payments)
- [x]  Overdue payments (5, and some message if there are more, counter?)

due on | name | amount | pay btn or paid label

**Comment by davidochoa** [comment]
@defeed what do you think about the items header? (due on | name | amount | pay btn or paid label)

**Comment by defeed** [comment]
@davidochoa that should be enough, I'll make it look nice

**Comment by davidochoa** [comment]
Nice!! :D

**Comment by davidochoa** [comment]
@defeed you forgot to link it to the issue, to have some nice github flow :D

**Comment by defeed** [comment]
@davidochoa daayumm, forgot about that
